### ISSUE TITLE
torrentByEnclosure and URL redirect issue

### ISSUE THREAD

**Issue by eteubert** [astro/bitlove-ui#18]
Hey astro,

At the moment the `torrentByEnclosure` widget isn't working at all. I can't figure out which URL I have to put into it to make it work. I think @timpritlove has already told you but the best would be if you would follow redirects, so you can match URLs.

But right now I can't get it to work at all.

Example: **NSFW089 Spitzbübisch feixend**

In `http://bitlove.org/metaebene/not-safe-for-work/feed` the following two enclosure URLs are mentioned:

- `http://bitlove.org/metaebene/not-safe-for-work/nsfw089-spitzbuebisch-feixend.m4a.torrent` (enclosure, but I shouldn't need that)
- `http://not-safe-for-work.de/podlove/file/1761/s/feed/c/m4a/nsfw089-spitzbuebisch-feixend.m4a` (feedburner:origEnclosureLink)

The native URL is `http://meta.metaebene.me/media/nsfw/nsfw083-darmspiegel-online.m4a?ptm_source=download&ptm_context=select-show&ptm_file=nsfw083-darmspiegel-online.m4a`.

None of them match when I pass them `torrentByEnclosure`:

![screen shot 2014-07-22 at 13 40 05](https://cloud.githubusercontent.com/assets/235918/3654082/b51d34d6-1162-11e4-885b-8f53683610c6.png)

So I am a bit confused. What can I do to make it work on my end?

**Comment by astro** [comment]
Fixed in https://github.com/astro/prittorrent/issues/33
