### ISSUE TITLE
solve "no_content_length"-errors, by falling back to "length"-parameter in enclosure?

### ISSUE THREAD

**Issue by katrinleinweber** [astro/bitlove-ui#19]
moved from https://github.com/astro/bitlove-ui/issues/18#issuecomment-64944193
> [...] `no_content_length` error messages (for each episode that has a /podlove/file/tracking URL) [...]

> [...] server is not supplying the `Content-Length:` header. Are you generating download files on the fly? :)

It's a webhosting service, so I'm not sure I can influence what it sends or generates. However, there is definitely a `length` parameter in each file's `<enclosure />` (with Podlove Tracking switched on). Can Bitlove be made to fall back to that one?

**Comment by astro** [comment]
Everything has been looking fine to me, except for the link to kns006.

**Comment by katrinleinweber** [comment]
Wrong redirect; fixed now. Thank you!
