### ISSUE TITLE
Don't choke on feeds with encoding errors

### ISSUE THREAD

**Issue by zealot128** [astro/bitlove-ui#23]
Hey,

i just tried to fetch all Bitlove feeds to automatically import them into Podfilter :)

Then I noticed that some feeds produce 500 errors:
http://bitlove.org/landfunker/landfunker/feed

cheers!

**Comment by astro** [comment]
Thank you for reporting. I sincerely hope you enjoyed the error page.

```2015-06-17T21:40:06.12819 InternalError "SqlError {seState = \"22021\", seNativeError = 7, seErrorMsg = \"execute: PGRES_FATAL_ERROR: ERROR:  invalid byte sequence for encoding \\\"UTF8\\\": 0xfc\\n\"}"```

Looks like I should be more wary with input. Postponing this issue to another date... Of course, the correct fix would be in the source file itself. :-)

**Comment by astro** [comment]
This particular feed (which goes back to episode one) displays fine by now. In the meanwhile, I've swapped `HDBC` with `postgresql-libpq`.
