### ISSUE TITLE
encoding issue in feed?

### ISSUE THREAD

**Issue by carstenmichel** [astro/bitlove-ui#24]
curl https://bitlove.org/methodischinkorrekt/mp3-cdn/feed > /tmp/min.rss
xmllint /tmp/min.rss

creates errors:

/tmp/min.rss:101: parser error : Char 0xDE09 out of allowed range
&lt;img src="https://s.w.org/images/core/emoji/2.2.1/72x72/1f609.png" alt="😉
                                                                              ^
/tmp/min.rss:101: parser error : PCDATA invalid Char value 56841
&lt;img src="https://s.w.org/images/core/emoji/2.2.1/72x72/1f609.png" alt="😉
                                                                              ^
/tmp/min.rss:447: parser error : Char 0xDE09 out of allowed range
&lt;img src="https://s.w.org/images/core/emoji/2.2.1/72x72/1f609.png" alt="😉
                                                                              ^
/tmp/min.rss:447: parser error : PCDATA invalid Char value 56841
&lt;img src="https://s.w.org/images/core/emoji/2.2.1/72x72/1f609.png" alt="😉

**Comment by astro** [comment]
Dependencies have been updated in the meanwhile, and this feed works for me right now. Thank you for reporting!
